Feature/new project
AnnaYedoshina/QA24_TestRailDiploma_Yedoshina pull request #1
Opened 2023-08-03 12:03 UTC by AnnaYedoshina

2023-08-06 20:08 UTC, voropa requested changes

2023-08-06 20:08 UTC, voropa commented on Jenkinsfile
> +        choice (name: 'BROWSER', choices: ['chrome', 'safari'], description: 'Select a browser')
у вас параметры BBROWSER и HEADLESS нигде в java коде не  используютс потом, когда вы их из Jenkins файла передаете, так какой смысл от них? Еслии хотите сделать параметризированый запуск, то доделайте до конца, чтобы это работало

2023-08-06 20:08 UTC, voropa commented on src/test/java/api_tests/CasesApiTests.java
> +        Project project = Project.builder()
А зачем вы тут еще один Project создаете, еслион у вас и так в BaseApiTst создается перед всем сьютом?

2023-08-06 20:08 UTC, voropa commented on src/test/java/api_tests/CasesApiTests.java
> +        Assert.assertEquals(response.jsonPath().getString("title"), title);
А чего только title проверяете,  а остальные параметры?

2023-08-06 20:08 UTC, voropa commented on src/test/java/api_tests/MilestoneApiTests.java
> +        Assert.assertEquals(response.jsonPath().getString("name"), NAME);
Тут в GET запросе тоже, почему только Name проверяете?

2023-08-06 20:08 UTC, voropa commented on src/test/java/api_tests/MilestoneApiTests.java
> +                .setDescription("New features added")
Чего description тут при апдейте не меняете?

2023-08-06 20:08 UTC, voropa commented on src/test/java/api_tests/ProjectApiTests.java
> +        Assert.assertEquals(response.jsonPath().getString("name"), "New project");
И тут, снова, только namе проверяете

2023-08-06 20:08 UTC, voropa commented on src/test/java/api_tests/ProjectApiTests.java
> +        File file = new File(System.getProperty("user.dir") + "/src/test/resources/requestProjectBody.json");
Достаточно одного теста на createProject, просто добавьте сюда проверку тела ответа, а следующий тест удалите

2023-08-06 20:08 UTC, voropa commented on src/test/java/controllers/CasesController.java
> +                .statusCode(200)
Вы же вроде вынесли проверку статус кодов в сами тесты, почистите тогда тут в контроллерах эти проверки

2023-08-06 20:08 UTC, voropa commented on src/test/java/controllers/TestCasesController.java
> +public class TestCasesController {
Зачес тут этот пустой класс?

2023-08-06 20:08 UTC, voropa commented on src/test/java/pages/AddTestCasePage.java
> +            Thread.sleep(2000);
А почему тут Thread.sleep()? Замените на явное ожидание его

2023-08-06 20:08 UTC, voropa commented on src/test/java/pages/AddTestCasePage.java
> +        new Input(driver,FILE_INPUT).setValue(System.getProperty("user.dir") + "/src/test/resources/TestRail.jpg");
Пусть к картинке не должен быть захардкодан в методе странице, а должен передаваться сюда в качетсве входного аргумента

2023-08-06 20:08 UTC, voropa commented on src/test/java/pages/AddTestCasePage.java
> +        log.info("Clicking addNewButton");
Текст лога неправильный

2023-08-06 20:08 UTC, voropa commented on src/test/java/pages/AddTestCasePage.java
> +            Thread.sleep(5000);
и тут чего Thread.sleep()? замените на явное ожидание, если оно вообще тут нужно

2023-08-06 20:08 UTC, voropa commented on src/test/java/pages/AddTestCasePage.java
> +
Зачем тут лишние пробелы, отформатируйте

2023-08-06 20:08 UTC, voropa commented on src/test/java/pages/AllProjectsPage.java
> +    public String projectLinkLocator = "//a[text() = '%s']";
А почему эти локаторы public?

2023-08-06 20:08 UTC, voropa commented on src/test/java/pages/DashboardPage.java
> +        log.info("Opening Dashboard page");
Почему тут сначала try() ии попытка словить alert, а только  потом в catch() идет  driver.get(BASE_URL + "index.php?/dashboard");
Так не будет работать, вспоминайте, обсуждали с вами на консультации

2023-08-06 20:08 UTC, voropa commented on src/test/java/pages/DashboardPage.java
> +public class DashboardPage extends BasePage {
Смотрю, что у вас  есть AdministrationPage, DashboardPage и AllProjectsPage и на всех этих страницах действиия по созданию, удалению и редактировнию одной и той же сущности - проекта. 
Может это одна и та же страница? Проверьте. может вы переусложнили и насоздавали лишних PObjectов

2023-08-06 20:08 UTC, voropa commented on src/test/java/pages/DashboardPage.java
> +
лишняя строка пустая

2023-08-06 20:08 UTC, voropa commented on src/test/java/pages/DashboardPage.java
> +    public void openProject(String projectName) {
А чего тут нет аннотациии @Step? Это же тоже действие
Вообще  проверьте  по всем страницам  добавьте аннотиицию степ, не на всех действииях (методах) она у вас есть

2023-08-06 20:08 UTC, voropa commented on src/test/java/pages/LoginPage.java
> +    private String emailInputId = "name";
А тут чего локаторы стрингами, а не By? Сделайте одинаково, как в других Page  классах

2023-08-06 20:08 UTC, voropa commented on src/test/java/pages/MilestonesTab.java
> +    private static final By PENDO_IMAGE = By.xpath("//img[contains(@id,'pendo-image-badge')]");
У вас этот элемент (локатор) PENDO_INAGE будлируется в омногих классах. Вынесите его в BasePage и метод по ожиданию его тоже в BasePage

2023-08-06 20:08 UTC, voropa commented on src/test/java/pages/MilestonesTab.java
> +        try {
И тут перепутаны местами действия с алертом

2023-08-06 20:08 UTC, voropa commented on src/test/java/pages/MilestonesTab.java
> +        try {
Странно, что у вас внутри страницы milestonesPage метод openMilestoneTab(). Вы же по идее еще не находитесь на ней, когда ее открываете, а тут получается, что нужно вызывать метод openMilestoneTab из страницы milestonesPage - не логично

2023-08-06 20:08 UTC, voropa commented on src/test/java/pages/MilestonesTab.java
> +    private boolean isEntityExist(String entityName, By entityLocator) {
А зачем вам такой абстрактный (по названию) метод внутри страницы milestoenes? Тут же только с milesotnes работа идет, других сущностей нет. 
Назовите его isMilestoneExist

2023-08-06 20:08 UTC, voropa commented on src/test/java/pages/MilestonesTab.java
> +    private void clickIcon(String entityName, String entityTitleLocator, String iconActionLocator) {
1) Private методы должны следовать после public методов.
2) Удалите отсюда логирование ии лучше добавьте конкретный лог в  методы clickDeleteMilestone и clickEditMilestone, а не как тут "click delete/edit"

2023-08-06 20:08 UTC, voropa commented on src/test/java/pages/MilestonesTab.java
> +        wait.until(ExpectedConditions.visibilityOfElementLocated(WARNING_MESSAGE_IN_CONFIRMATION_DELETE_MILESTONE_WINDOW));
Вообще для модальных окон создают отдельный классы - page object'ы, в которых 2-3 метода, типа confirm(), close()
Зачастую модальные окна во всем приложении на разных страницах одинаковые, может отличаться только текст кнопок. 
Так что я бы посоветовал вам создать отдельный класс типа ConfirmationModal и в нем описать пару методов для обработки модального окна

2023-08-06 20:08 UTC, voropa commented on src/test/java/pages/TestCaseInfoPage.java
> +    private static final By PENDO_IMAGE = By.xpath("//img[contains(@id,'pendo-image-badge')]");
Про это я уже писал, что нужно вынести его в basePage

2023-08-06 20:08 UTC, voropa commented on src/test/java/pages/TestCaseInfoPage.java
> +                .setType(driver.findElement(By.id("cell_type_id")).getText().substring(5))
Так, а чего тут локаторы захардкоданы прямо в методе? Вынесите их в качестве полей класса, как в других страницах

2023-08-06 20:08 UTC, voropa commented on src/test/java/pages/TestCaseInfoPage.java
> +        return true;
У вас этот метод всегда возвращает true? почему так?

2023-08-06 20:08 UTC, voropa commented on src/test/java/pages/TestCaseInfoPage.java
> +        WebElement uploadedFile = driver.findElement(By.xpath("//div[contains(@title, 'TestRail')]"));
Еще и названеи файла захардкодано в локаторе - плохо

2023-08-06 20:08 UTC, voropa commented on src/test/java/pages/TestCasesTab.java
> +    private boolean isEntityExist(String entityName, By entityLocator) {
И тут тоже абстрактный метод, еще и один в один как в milestonesPage. 
Смотрите, у вас эти 2 страницы : cases и milestones очень похожи и внешне и по функционалу, да и локаторы почти одинаковые, отличаются только сами сущности (их названия)
И вы дублируете одни и те же локатры, методы и т.д на этих страницах.

Сделайте вот что:  создайте общую абстратную страницу для них типа BaseTabPage, опишите в этом классе все общие локаторы и методы, которые одинаковы для всех Tab'ов, потом наследуйте эти 2 page класса от BaseTabPage и  переопределяйте, дописывайте тут только нужные уникальные методы и локаторы, которых нет в BaseTabPage

2023-08-06 20:08 UTC, voropa commented on src/test/java/pages/TestCasesTab.java
> +        log.info("Opening page containing Sections and Cases");
И тут с методом open намудрили что-то

2023-08-06 20:08 UTC, voropa commented on src/test/java/pages/TestCasesTab.java
> +    @Step("Creating new section with title '{newSectionName}'")
А чего методы для работы с section у вас в TestCasesTab? По идее это должны быть отдельная страница

2023-08-06 20:08 UTC, voropa commented on src/test/java/tests/BaseTest.java
> +    protected WebDriverWait wait;
IDEA подсвечивает, что это поле wait нигде не используется, удалите его в таком случае

2023-08-06 20:08 UTC, voropa commented on src/test/java/tests/BaseTest.java
> +    public void setUp(@Optional("chrome") String browserName, ITestContext context) throws Exception {
Вы тут получаете browser как параметр из testng.xml фалов, но в самих .xml файлах он есть только в smoke

2023-08-06 20:08 UTC, voropa commented on src/test/java/tests/LoginTests.java
> +    public void negativeLoginTestData(String username, String password, String expectedErrorMessage) {
Почему у вас сам тест называется так же, как и dataProvider метод?

2023-08-06 20:08 UTC, voropa commented on src/test/java/tests/MilestonesTest.java
> +    public void addMilestone() {
Почему addMilestone? я бы назвал loginAndOpenMilestoinesTab, чтобы было понятнее

2023-08-06 20:08 UTC, voropa commented on src/test/java/tests/MilestonesTest.java
> +    public void createMilestoneTest() throws InterruptedException {
Зачем тут throws  InterruptedException?

2023-08-06 20:08 UTC, voropa commented on src/test/java/tests/MilestonesTest.java
> +        String milestoneName = faker.animal().name() + faker.number().randomDigit();
Я же говорил про TestDataGenerator, вы туда вынесли только testCase,а данные для остальных тестоы почему не вынесли?

2023-08-06 20:08 UTC, voropa commented on src/test/java/tests/ProjectTest.java
> +        String projectName = faker.app().name() + faker.number().randomDigit();
То же саммое, вынесите в testDataGenerator, у ваас же даже дата модели есть для всех этих сущностей, вот их и используйте

2023-08-06 20:08 UTC, voropa commented on src/test/java/utils/TestDataGenerator.java
> +    public static TestCase negativeTestCaseGeneration(String title){
Зачем сюда входным аргументом епредавать title, если он не используется и выставляется путсым:
 .setTitle("")?

2023-08-06 20:08 UTC, voropa commented on src/test/resources/config.properties
> +browser=chrome
Порперти browser и headless у вас нигде не используются

2023-08-06 20:09 UTC, voropa requested changes
Исправляйте замечания, их, к сожалению, не мало

2023-08-07 13:32 UTC, voropa requested changes

2023-08-07 13:32 UTC, voropa commented on src/test/java/pages/AddTestCasePage.java
> +    private String filePath = System.getProperty("user.dir") + "/src/test/resources/TestRail.jpg";
FilePath - это по  сути тестовые данные, а тестовые данные не должны храниться в Page классе. Они должны передаваться в page класс в виде входного аргумента какой-то функции. Переделайте.

2023-08-07 13:32 UTC, voropa commented on src/test/java/utils/TestDataGenerator.java
> +    public static Project projectGeneration() {
А в чем отличие этих двух метрдов: projectGeneration и updatedProjectGeneration? Они же возвращают одинаковые обьекты с разными рандомными данными? Так зачем дублировать второй метод, если можно один и тот же 2 раза вызвать в тесте просто и получите 2 разных обьекта (с разными рандомными данными)

2023-08-07 13:32 UTC, voropa commented on src/test/java/utils/TestDataGenerator.java
> +    public static Project projectGeneration() {
То же самое для других сущностей

2023-08-07 17:55 UTC, voropa requested changes

2023-08-07 17:55 UTC, voropa commented on src/test/java/tests/BaseTest.java
> +    protected final static String WRONG_USERNAME = "ayqa245@mailinator.com";
У вас эти 2 константы (WRONG_USERNAME/PASS) и спользуются только в loginTest, так что переместите их в LOginTests класс, зачем хранить их в BaseTest

2023-08-07 17:55 UTC, voropa commented on src/test/java/tests/BaseTest.java
> +    protected final static String NAME = "TestProject";
Не информативное название константы NAME, переименуйте в PROJECT_NAME

2023-08-07 17:55 UTC, voropa commented on src/test/java/tests/BaseTest.java
> +    static Faker faker = new Faker();
faker уже нигде не используется, так как вы перенесли все в TestDataGenerator, удалите его отсюда

2023-08-07 17:55 UTC, voropa commented on src/test/java/tests/MilestonesTest.java
> +        dashboardPage.openProject("TestProject");
Чего вы тут захардкодили название проекта "TestProject", у вас же есть константа с названием проекта в BaseTest, используйте ее тут. В тестах на Sections, TestCases то же самое

2023-08-07 17:55 UTC, voropa commented on src/test/java/pages/LoginPage.java
> +    private By errorMessage = By.cssSelector(".loginpage-message");
А чего эти 2 локатора errorMessage и errorText оставиили private By, а не как остальные private static final By? Сделайте везде одинаково

2023-08-07 20:02 UTC, voropa requested changes

2023-08-07 20:02 UTC, voropa commented on src/test/java/pages/AdministrationPage.java
> +    private static final String deleteProjectIconLocator = "//*[contains(text(),'%s')]/ancestor::tr/descendant::div[contains(@class,'icon-small-delete')]";
Если вы обьявляете константы как private static final, то их названяи должны быть соотвественно в UPPER_CASE  согласно java code convention

2023-08-08 09:14 UTC, AnnaYedoshina commented on src/test/java/api_tests/CasesApiTests.java
> +        Project project = Project.builder()
Почему-то без этого куска кода когда запускаю сьют апи не проходят casesApiTest. В классе проходят, а в сьюте - нет

2023-08-08 09:38 UTC, AnnaYedoshina commented on src/test/java/api_tests/ProjectApiTests.java
> +        File file = new File(System.getProperty("user.dir") + "/src/test/resources/requestProjectBody.json");
Вы же на занятии говорили, что из файла не получится. И что только статус код получится проверить...

2023-08-08 09:45 UTC, AnnaYedoshina commented on src/test/java/pages/MilestonesTab.java
> +        wait.until(ExpectedConditions.visibilityOfElementLocated(WARNING_MESSAGE_IN_CONFIRMATION_DELETE_MILESTONE_WINDOW));
Локаторы отличаются у текста в окне, а я их использую для wait

2023-08-08 18:38 UTC, voropa requested changes

2023-08-08 18:38 UTC, voropa commented on src/test/java/api_tests/CasesApiTests.java
> +        Project project = Project.builder()
Предполагаю, что это из-за того, что у вас в BaseApiTest ест ьпеременная projectId - в которой id глобального проекта, который создается для всех ап тестов один раз. А потом в ProjectsApiTests у вас есть такая же переменная projectId, где храниться id проекта только для этих тестов. Но из-за того, что названия переменных одинаковые и классы наследуются, то это по  факту одна и та же переменная, которая переопрределяется. И скорее всего, тесты на проекты идут в сьюте раньше, чем тесты на cases и в AfterClass для проектов удаляется проект (глобальный). Сделайте разные названия для этих переменных (полей) и проверьте. Странно, что java компилятор на такое не ругается вообще...

2023-08-08 18:38 UTC, voropa commented on src/test/java/api_tests/ProjectApiTests.java
> +        File file = new File(System.getProperty("user.dir") + "/src/test/resources/requestProjectBody.json");
Можно, сравнивать с тем же файлом, что и передаете в request body. Только нужно немного кода  пописать, чтобы из файла вытащить JSON обьект и десериализовать его в JAVA обьект
        String filePath = System.getProperty("user.dir") + "/src/test/resources/requestProjectBody.json";
        Project expectedProject = null;
        try {
            expectedProject = new Gson().fromJson(Files.readString(Paths.get(filePath)), Project.class);
        } catch (IOException e) {
            e.printStackTrace();
        }

        Response response = projectController.addProject(new File(filePath));
        Assert.assertEquals(response.getStatusCode(), 200);
        Assert.assertEquals(response.getBody().as(Project.class, ObjectMapperType.GSON), expectedProject);

2023-08-08 19:16 UTC, AnnaYedoshina commented on src/test/java/api_tests/ProjectApiTests.java
> +        File file = new File(System.getProperty("user.dir") + "/src/test/resources/requestProjectBody.json");
Изменила, но не могу сделать resolve, нет этой кнопки.

2023-08-08 19:17 UTC, AnnaYedoshina commented on src/test/java/pages/TestCasesTab.java
> +    @Step("Creating new section with title '{newSectionName}'")
testcases и sections в одном табе

2023-08-09 08:01 UTC, AnnaYedoshina commented on src/test/java/pages/TestCasesTab.java
> +    private boolean isEntityExist(String entityName, By entityLocator) {
Я вынесла пару методов.

2023-08-09 10:29 UTC, voropa requested changes

2023-08-09 10:29 UTC, voropa commented on src/test/java/api_tests/ProjectApiTests.java
> +        Assert.assertEquals(response.jsonPath().getString("name"), "New project");
А зачем тут проверять name отдельно, если на следующей строчке (39) у вас assert, который проыеряет целиком весь обьект

2023-08-09 10:29 UTC, voropa commented on src/test/java/api_tests/ProjectApiTests.java
> +        String filePath = System.getProperty("user.dir") + "/src/test/resources/requestProjectBody.json";
Вы 2 раза тут дублируете System.getProperty("user.dir") + "/src/test/resources/requestProjectBody.json";
Используйте переменную filePath для new File() на строчке 45

2023-08-09 10:29 UTC, voropa commented on src/test/java/api_tests/ProjectApiTests.java
> -    @Test(description = "Check if the project can be updaetd by API", priority = 4, groups = "api")
А чего вы удалил тест на updateProject???

2023-08-09 10:29 UTC, voropa commented on src/test/java/pages/BaseTabPage.java
> +    public boolean isEntityExist(String entityName, By entityLocator) {
А чего только метод isEntityExist вынесли сюда, у вас как минимум еще есть там метод clickIcon, который дублируется в двух классах

2023-08-09 10:40 UTC, voropa requested changes

2023-08-09 10:40 UTC, voropa commented on src/test/java/pages/DashboardPage.java
> +        try {
У вас логика с алертом много где используется, вынесите этот кусок кода в отдельный метод с названием acceptAlertIfPresent() и переиспользуйте его везде

2023-08-09 10:40 UTC, voropa commented on src/test/java/pages/TestCaseInfoPage.java
> +        WebElement uploadedFile = driver.findElement(By.xpath("//div[contains(@title, 'TestRail')]"));
Все еще актуальный коментарий. Поменяйте локатор или сделайте имя фала входным аргументов в этой функциии, чтобы не было захардкодано название файла в локаторе!

2023-08-09 10:40 UTC, voropa commented on src/test/java/pages/TestCasesTab.java
> +    String deleteSectionIconLocator = "//span[contains(@id,'sectionName') and text()='%s']/parent::div/descendant::div[contains(@class,'icon-small-delete')]";
а чего тут у вас локаторы на строках 31 - 34 без модификаторов доступа вообще, просто String?

2023-08-09 10:40 UTC, voropa commented on src/test/java/pages/TestCasesTab.java
> +    public void clickIcon(String entityName, String entityTitleLocator, String iconActionLocator) {
Этот метод еще и public, он же ииспользуется только внутри класса, значит должен быть private/protected

2023-08-09 10:40 UTC, voropa commented on src/test/java/tests/LoginTests.java
> +    protected final static String WRONG_USERNAME = "ayqa245@mailinator.com";
А зачем они тут protected? От LoginPage же ничего не наследуется

2023-08-09 10:40 UTC, voropa commented on src/test/java/utils/TestDataGenerator.java
> +    public static Project projectGeneration() {
Все еще акутально, у вас по-прежнему 2 одинаковых метоода тут: projectGeneration и updatedProjectGeneration

2023-08-09 10:44 UTC, AnnaYedoshina commented on src/test/java/pages/BaseTabPage.java
> +    public boolean isEntityExist(String entityName, By entityLocator) {
У меня не получается(

2023-08-09 10:45 UTC, voropa commented on src/test/java/pages/BaseTabPage.java
> +    public boolean isEntityExist(String entityName, By entityLocator) {
А что именно не получается? Опишите проблему

2023-08-09 11:23 UTC, AnnaYedoshina commented on src/test/java/pages/BaseTabPage.java
> +    public boolean isEntityExist(String entityName, By entityLocator) {
Вроде получилось, скоро пришлю, проверяю

2023-08-09 11:26 UTC, voropa requested changes

2023-08-09 11:26 UTC, voropa commented on src/test/java/api_tests/BaseApiTest.java
> +    @BeforeSuite(alwaysRun = true)
Вот в чем проблема:
https://stackoverflow.com/questions/33626558/global-variables-are-set-to-null-after-first-class-execution-in-test-ng
Из-за этого в сьюте у вас не проходит casesTest, потому что projectId становиться null.
Не получиться использовать BeforeSuite и создавать проект один раз для всех тестов. Так что:
1 )поменяйте Bfore/AfterSuite на Before/AfterClass - будет создаваться проект перед каждым классом.
2) Для ProjectsApiTest удалите before/after, они там будут не  нужны, и так проект юудет создаваться в BaseApiTest
3) Уберите создание проекта в BeforeClass для casesApiTsts

2023-08-09 11:34 UTC, AnnaYedoshina commented on src/test/java/pages/BaseTabPage.java
> +    public boolean isEntityExist(String entityName, By entityLocator) {
не проходит. У caseLocator и milestoneLocator локаторы одинаковые, я вынесла в baseTab как один entityLocator. и написала метод     
protected void clickIcon(String entityName, String entityTitleLocator, String iconActionLocator) {
        wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(String.format(ENTITY_LOCATOR, entityName))));
        scroll(entityTitleLocator, entityName);
        hover(entityTitleLocator, entityName);
        WebElement icon = driver.findElement(By.xpath(String.format(iconActionLocator, entityName)));
        wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(String.format(iconActionLocator, entityName))));
        log.info("Click edit/delete icon");
        icon.click();
section тесты проходят, а milestone-нет

2023-08-09 11:37 UTC, voropa commented on src/test/java/pages/BaseTabPage.java
> +    public boolean isEntityExist(String entityName, By entityLocator) {
А что значит не проходит? Какую ошибку выдает, на каком шаге падает?

2023-08-09 11:42 UTC, AnnaYedoshina commented on src/test/java/pages/BaseTabPage.java
> +    public boolean isEntityExist(String entityName, By entityLocator) {
на click icon и падает

2023-08-09 11:44 UTC, AnnaYedoshina commented on src/test/java/api_tests/BaseApiTest.java
> +    @BeforeSuite(alwaysRun = true)
все сделала, но когда в ProjectsApiTest удаляю, они не проходят. Если оставляю, то все работает

2023-08-09 11:46 UTC, AnnaYedoshina commented on src/test/java/api_tests/BaseApiTest.java
> +    @BeforeSuite(alwaysRun = true)
"error": "Field :project_id is not a valid or accessible project." вот твкое выдает

2023-08-09 11:46 UTC, voropa commented on src/test/java/pages/BaseTabPage.java
> +    public boolean isEntityExist(String entityName, By entityLocator) {
Так а ошибка какая??

2023-08-09 11:49 UTC, AnnaYedoshina commented on src/test/java/pages/BaseTabPage.java
> +    public boolean isEntityExist(String entityName, By entityLocator) {
org.openqa.selenium.TimeoutException: Expected condition failed: waiting for visibility of element located by By.xpath: //div[contains(@class,'grid-container')]/descendant::span[text()='Togo2'] (tried for 20 second(s) with 500 milliseconds interval)

2023-08-09 13:17 UTC, voropa requested changes

2023-08-09 13:17 UTC, voropa commented on src/test/java/api_tests/ProjectApiTests.java
> +        Project project = Project.builder()
У вас в ProjectApiTests почти в каждом методе и тесте дублируется один и тот же обьект:
Project project = Project.builder()
                .setName("New project")
                .setAnnouncement("Project to check")
                .setShowAnnouncement(false)
                .setSuiteMode(1)
                .build();
Зачем? Создайте его один раз в before и потом используйте во всех методах. А в тесте на апдейт он тоже используется и получается, что ничего не апдейтиться в проекте, с такимми же значениями обьект отправляется, какой тогда смысл от теста на апдейт?

2023-08-09 13:17 UTC, voropa commented on src/test/java/api_tests/ProjectApiTests.java
> +    private int projectId;
И все же, уберите отсюда BeforeClass с созданием нового проекта и переменную private int projectId;
У вас все это есть в BaseApiTest, зачем тут делать то же саамое?

2023-08-09 13:40 UTC, AnnaYedoshina commented on src/test/java/api_tests/ProjectApiTests.java
> +        Project project = Project.builder()
если я удаляю , то от куда мне получать project для assert?
Assert.assertEquals(response.getBody().as(Project.class, ObjectMapperType.GSON), project);

2023-08-09 13:40 UTC, AnnaYedoshina commented on src/test/java/api_tests/ProjectApiTests.java
> +    private int projectId;
так тесты не проходят без этого

2023-08-10 16:29 UTC, voropa requested changes

2023-08-10 16:29 UTC, voropa commented on pom.xml
> +        <dependency>
Зачем вы опять JUnit зависимость добаавили?

2023-08-10 16:29 UTC, voropa commented on src/test/java/pages/BasePage.java
> +    public void scrollIntoView(String locator) {
Так а почему вы их в  BasePage добавили, а не в Button декоратор, как я показывал???

2023-08-10 16:42 UTC, AnnaYedoshina commented on src/test/java/pages/BasePage.java
> +    public void scrollIntoView(String locator) {
я запуталась с button и scroll и hover жe к milestoneLocator, а не к кнопке. Не получилось, короче. А так не правильно?

2023-08-10 16:44 UTC, voropa commented on src/test/java/pages/BasePage.java
> +    public void scrollIntoView(String locator) {
Нет, так не  правильно. scroll и hover должны быть в декораторах

2023-08-10 17:08 UTC, AnnaYedoshina commented on src/test/java/pages/BasePage.java
> +    public void scrollIntoView(String locator) {
Хорошо, пробую так.
Добавила в Button 
public void scroll() {
       this.element.scrollIntoView();
    }

    public void hover() {
        actions.moveToElement(this.element).build().perform();

    }
и потом в clickEditMilestone сдедующее
 public void clickEditMilestone(String milestoneName) {
        log.info("Clicking edit Milestone");
        waitForPendoBubbleImage();
        String milestoneLocator = String.format(MILESTONE_LOCATOR, milestoneName);
        String editMilestoneLocator = String.format(EDIT_MILESTONE_LOCATOR, milestoneName);
        waitForElementVisibility(milestoneLocator);
        new Button(driver,milestoneLocator).scroll();
        new Button(driver,milestoneLocator).hover();
        WebElement editIcon = driver.findElement(By.xpath(editMilestoneLocator));
        waitForElementVisibility(editMilestoneLocator);
        editIcon.click();
    }
на scroll падает

2023-08-10 17:19 UTC, AnnaYedoshina commented on src/test/java/pages/BasePage.java
> +    public void scrollIntoView(String locator) {
и так тоже не получается, я видимо, что-то упустила...
 public void clickEditMilestone(String milestoneName) {
        log.info("Clicking edit Milestone");
        waitForPendoBubbleImage();
        String milestoneLocator = String.format(MILESTONE_LOCATOR, milestoneName);
        String editMilestoneLocator = String.format(EDIT_MILESTONE_LOCATOR, milestoneName);
        waitForElementVisibility(milestoneLocator);
        Button milestoneButton = new Button(driver, milestoneLocator);
        milestoneButton.scroll();
        milestoneButton.hover();
        WebElement editIcon = driver.findElement(By.xpath(editMilestoneLocator));
        waitForElementVisibility(editMilestoneLocator);
        editIcon.click();
    }

2023-08-14 11:32 UTC, voropa requested changes

2023-08-14 11:32 UTC, voropa commented on src/test/java/utils/DeleteCheckBoxModal.java
> +public class DeleteCheckBoxModal {
1. Создайте пакет 'modals' и туда поместите эти классы с диалогами, а не в utils храните их.
2. Используйте наследование. У вас один диалог (с чекбоксом) расширяет функционал другого (который без чекбокса), так что унаследуйте один от другого.
3. Добавьте в базовый класс диалога метод  waitForDisplayed(), который будет дожидаться, пока диалог появиться (например EC.visibilityOf('//*[@id=deleteDialog]')). Вызывайте его в тестах потом, прежде, чем нажимать кнопки в диалоге.

2023-08-14 11:32 UTC, voropa commented on src/test/java/pages/AdministrationPage.java
> +        DeleteCheckBoxModal deleteCheckBoxModal = new DeleteCheckBoxModal(driver);
1. Инициализируйте эти обьекты (диалоги) точно так же как и пэйджи, один раз в beforeClass, а не каждый раз как тут в методе.
2. Когда примените наследование, про которое я писал выше, вам не придется обращаться к двум разным диалогам, а оба метода можно и нужно будет вызвать у deleteCheckBoxModal

2023-08-14 11:32 UTC, voropa commented on src/test/java/elements/Button.java
> +        this.actions = new Actions(driver);
Зачем вам тут Actions в конструкторе, они же нигде не используются потом?

2023-08-14 11:32 UTC, voropa commented on src/test/java/pages/TestCasesTab.java
> +        DeleteCheckBoxModal deleteCheckBoxModal = new DeleteCheckBoxModal(driver);
То же самое тут

2023-08-15 11:45 UTC, voropa commented on src/test/java/pages/MilestonesTab.java
> +        //waitForElementVisibility(milestoneLocator);
Чего закоментировано?

2023-08-16 11:54 UTC, voropa requested changes

2023-08-16 11:54 UTC, voropa commented on src/test/java/api_tests/MilestoneApiTests.java
> +        Milestone milestone = Milestone.builder()
В тесте на getMilestone вы создаете точно такой же обьект Milestone milestone. Так сделайте так же, как мы делали для project, обьявите обьект MIlestone milestone на уровне класса, создайте его в BeforeClass, а потом в тесте на  get переиспользуйте его

2023-08-16 11:54 UTC, voropa commented on src/test/java/api_tests/MilestoneApiTests.java
> +        Milestone milestone = Milestone.builder()
Для наглядности добавляйте тут другие значения name, description, отличные от тех, что в BeforeClass

2023-08-16 11:54 UTC, voropa commented on src/test/java/utils/TestDataGenerator.java
> +    public static Project projectGeneration() {
Оставьте только один метод из этих двух, они же одинаковые полностью, зачем их два?

2023-08-16 11:54 UTC, voropa commented on src/test/java/utils/TestDataGenerator.java
> +    public static TestCase positiveTestCaseGeneration(String title) {
А этот входной аргумент String title не используется нигде

2023-08-16 11:54 UTC, voropa commented on src/test/java/api_tests/MilestoneApiTests.java
> +                .setReferences("RF-1")
А вообще, у вас же есть TestDataGenerator, используйте его в API тестах тоже, чтобы генерились рандомные данные

2023-08-16 11:54 UTC, voropa commented on suites/smokeTest.xml
> +        <parameter name="browserName" value="chrome"/>
Чего у вас d  smokeTest.xml есть parameter BrowserName, а в regression.xml - нет?

2023-08-16 11:54 UTC, voropa commented on src/test/java/pages/TestCasesTab.java
> +        Actions actions = new Actions(driver);
Так а чего вы не вы сделали в Button декораторе метод hover(), а делаете этот hover тут в page методе?

2023-08-16 15:26 UTC, voropa requested changes

2023-08-16 15:26 UTC, voropa commented on src/test/java/elements/Button.java
> +    public void hover() {
Сделайте по  аналогии со scroll(). В MyElement  реализуйте метод hover(),  а тут в классе Button тоже метод hover(), который внтури будет вызывать element.hover(). Так будет правильнее и вам не придется инициализировать его тут в конструкторах класса Button

2023-08-16 15:26 UTC, voropa commented on src/test/java/elements/MyElement.java
> +    public WebElement getWebElement() {
Вот этот метод вам не понадобится

2023-08-16 15:37 UTC, voropa requested changes

2023-08-16 15:37 UTC, voropa commented on src/test/java/elements/Button.java
> +        this.driver = driver;
Соответсвенно уберите инициализацию драйвера с конструкторов класса Button ( this.driver = driver;) и сам атрибут private final WebDriver driver, он тут больше не нужен

2023-08-17 11:40 UTC, voropa requested changes

2023-08-17 11:40 UTC, voropa commented on src/test/java/pages/ProjectPage.java
>      @Step("Opening page containing Sections and Cases")
Поправьте текст в степе

2023-08-17 11:46 UTC, AnnaYedoshina commented on src/test/java/pages/ProjectPage.java
>      @Step("Opening page containing Sections and Cases")
done

2023-08-17 13:51 UTC, voropa approved these changes

2023-08-17 17:26 UTC, merged